name: CI
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python3 -c "import ciou; print(ciou.__version__)"
    - name: Run static analysis
      run: |
        pycodestyle ciou
        pylint -E --enable=invalid-name,unused-import,useless-object-inheritance ciou tst
    - name: Run unittests with coverage
      run: |
        coverage run --branch --source ciou/ -m unittest discover -s tst/
        coverage report -m
      if: matrix.os != 'windows-latest'
    - name: Run unittests
      run: |
        python3 -m unittest discover -s tst/
      if: matrix.os == 'windows-latest'
    # - name: Push coverage
    #   uses: paambaati/codeclimate-action@7bcf9e73c0ee77d178e72c0ec69f1a99c1afc1f3 # v2.7.5
    #   with:
    #     coverageCommand: coverage xml
    #     coverageLocations: |
    #       ${{github.workspace}}/coverage.xml:coverage.py
    #   env:
    #     CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
    #   if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10' && github.ref == 'refs/heads/main'
